#!/bin/bash

# 获取当前提交的 hash 值
commit_hash=$(git rev-parse --short HEAD)
current_time=$(date +"%Y-%m-%d %H:%M:%S")
# 修改脚本中的版本号
sed -i "s/version: v[0-9a-f]*/version: v$commit_hash/" ./scripts/core/component_manager.sh
sed -i "s/updateTime: .*/updateTime: $current_time\"/" ./scripts/core/component_manager.sh

./scripts/core/merge_script.sh
